[package]
name = "authenticator"
version = "0.1.0"
edition = "2024"

[dependencies]
totp-rs = "5.7.0"
eframe = "0.31.1"
egui = "0.31.1"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
aes-gcm = "0.10"
base64 = "0.22"
dirs-next = "2.0"
rand = "0.9"
sha2 = "0.10"